swarm:
  deployment:
    ${project.artifactId}.war:
      web:
        login-config:
          auth-method: "KEYCLOAK"
        security-constraints:
          - url-pattern: "/rest-api/*"
            roles: "[client]"
