swarm:
  deployment:
    ${project.build.finalName}.war:
      swagger:
        root: "/rest-api"
        title: "${project.artifactId}"
        version: "1"
        packages:
           - "com.gepardec.esb.prototype.services.app.configuration"
           - "com.gepardec.esb.prototype.services.app.rest"
